### ISSUE TITLE
Bug in episode 5, file 'activesearch.html'

### ISSUE THREAD

**Issue by KenanZ** [craigcode/Magic-Polyglot#1]
Line which produced an error :
hx-post="/magicscripts/mgrqispi.dll?appname=mgHTMX&prgname=Search"

have changed to:
hx-get="http://127.0.0.1/magicscripts/mgrqispi.dll?appname=mgHTMX&prgname=Search"

... and it is working fine.

**Comment by craigcode** [comment]
Thank you. I'll update. I must have made a last minute change to the demo without thinking it through. Appreciate you letting me know!
